Jumph\Bundle\TimeBundle\Entity\TimeTracker:
    type: entity
    table: jumph_time_tracker

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true

    manyToOne:
        project:
          targetEntity: \Jumph\Bundle\ProjectBundle\Entity\Project
          inversedBy: timeTrackers
          joinColumn:
            name: project_id
            referencedColumnName: id
          cascade: ["persist", "remove"]

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        category:
            type: string
            length: 150
        description:
            type: text
        date:
            type: date
        hours:
            type: decimal
            scale: 1
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true