parameters:
#    jumph_quotation.example.class: Jumph\Bundle\QuotationBundle\Example

services:
#    jumph_quotation.example:
#        class: %jumph_quotation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
