jumph_app:
    resource: "@JumphAppBundle/Resources/config/routing.yml"
    prefix:   /

jumph_dashboard:
    resource: "@JumphDashboardBundle/Resources/config/routing.yml"
    prefix:   /

jumph_auth:
    resource: "@JumphAuthBundle/Resources/config/routing.yml"
    prefix:   /

jumph_user:
    resource: "@JumphUserBundle/Resources/config/routing.yml"
    prefix:   /

jumph_quotation:
    resource: "@JumphQuotationBundle/Resources/config/routing.yml"
    prefix:   /

jumph_email:
    resource: "@JumphEmailBundle/Resources/config/routing.yml"
    prefix:   /

jumph_project:
    resource: "@JumphProjectBundle/Resources/config/routing.yml"
    prefix:   /

jumph_time:
    resource: "@JumphTimeBundle/Resources/config/routing.yml"
    prefix:   /

jumph_issue:
    resource: "@JumphIssueBundle/Resources/config/routing.yml"
    prefix:   /

