jumph_auth_register:
    path:  /register
    defaults: { _controller: JumphAuthBundle:Auth:register }
    methods:  [GET, POST]
jumph_auth_login:
    path:  /login
    defaults: { _controller: JumphAuthBundle:Auth:login }
    methods:  [GET]
jumph_auth_login_check:
    path: /login_check
    methods:  [POST]
jumph_auth_logout:
    path:  /logout
    methods:  [GET]