parameters:
#    jumph_auth.example.class: Jumph\Bundle\AuthBundle\Example

services:
#    jumph_auth.example:
#        class: %jumph_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
