parameters:
#    jumph_project.example.class: Jumph\Bundle\ProjectBundle\Example

services:
#    jumph_project.example:
#        class: %jumph_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
