services:
    jumph_project.project_manager:
        class: Jumph\Bundle\ProjectBundle\Manager\ProjectManager
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_project.project_menu_listener:
                class: Jumph\Bundle\ProjectBundle\EventListener\ProjectMenuListener
                tags:
                  - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuProject }
