Jumph\Bundle\ProjectBundle\Entity\Project:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
        company:
            - Valid: ~
        employee:
            - Valid: ~
        projectStatus:
            - Valid: ~

Jumph\Bundle\ProjectBundle\Entity\ProjectStatus:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3