services:
    jumph_project.project_filter:
        class: Jumph\Bundle\ProjectBundle\Filter\ProjectFilter
        arguments:
            - @jumph_project.project_manager
            - @lexik_form_filter.query_builder_updater
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_project.project_filter_name:
            class: Jumph\Bundle\ProjectBundle\Filter\Type\NameFilterType
            tags:
                - { name: form.type, alias: project_filter_name }
    jumph_project.filter_subscriber:
        class: Jumph\Bundle\ProjectBundle\Filter\Subscriber\FilterSubscriber
        tags:
            - { name: kernel.event_subscriber, alias: filter_subscriber }