Jumph\Bundle\ProjectBundle\Entity\Project:
    type: entity
    table: project

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true

    oneToOne:
        company:
          targetEntity: \Jumph\Bundle\ClientBundle\Entity\Company
          joinColumn:
            name: company_id
            referencedColumnName: id
        employee:
          targetEntity: \Jumph\Bundle\ClientBundle\Entity\Employee
          joinColumn:
            name: employee_id
            referencedColumnName: id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 150
        status:
            type: string
            length: 150
        description:
            type: text
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true