Jumph\Bundle\ProjectBundle\Entity\Project:
    type: entity
    table: jumph_project

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true

    manyToOne:
        company:
          targetEntity: \Jumph\Bundle\ClientBundle\Entity\Company
          inversedBy: projects
          joinColumn:
            name: company_id
            referencedColumnName: id
          cascade: ["persist", "remove"]
        employee:
          targetEntity: \Jumph\Bundle\ClientBundle\Entity\Employee
          inversedBy: projects
          joinColumn:
            name: employee_id
            referencedColumnName: id
          cascade: ["persist", "remove"]

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 150
        status:
            type: string
            length: 150
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true