services:
    jumph_email.email_manager:
        class: Jumph\Bundle\EmailBundle\Manager\EmailManager
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_email.email_menu_listener:
                class: Jumph\Bundle\EmailBundle\EventListener\EmailMenuListener
                tags:
                  - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuEmail }
