parameters:
    jumph_client.repository.company_manager.class: Jumph\Bundle\ClientBundle\Manager\CompanyManager
    jumph_client.repository.employee_manager.class: Jumph\Bundle\ClientBundle\Manager\EmployeeManager

services:
    jumph_client.company_manager:
        class: %jumph_client.repository.company_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_client.employee_manager:
        class: %jumph_client.repository.employee_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_client.client_menu_listener:
                class: Jumph\Bundle\ClientBundle\EventListener\ClientMenuListener
                tags:
                  - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuClient }
