services:
    jumph_time_tracker.time_tracker_manager:
        class: Jumph\Bundle\TimeTrackerBundle\Manager\TimeTrackerManager
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setPaginator, [ @knp_paginator ] ]
    jumph_time_tracker.time_menu_listener:
        class: Jumph\Bundle\TimeTrackerBundle\EventListener\TimeMenuListener
        tags:
          - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuTime }
          - { name: kernel.event_listener, event: jumph.build_config_menu, method: onConfigMenuTime }
