parameters:
#    jumph_issue.example.class: Jumph\Bundle\IssueBundle\Example

services:
#    jumph_issue.example:
#        class: %jumph_issue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
