parameters:
#    jumph_time.example.class: Jumph\Bundle\TimeBundle\Example

services:
#    jumph_time.example:
#        class: %jumph_time.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
