parameters:
#    jumph_time.example.class: Jumph\Bundle\TimeBundle\Example

services:
    jumph_time.time_menu_listener:
                class: Jumph\Bundle\TimeBundle\EventListener\TimeMenuListener
                tags:
                  - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuTime }
