parameters:
    jumph_app.session.alert_message.class: Jumph\Bundle\AppBundle\Session\AlertMessage

services:
    jumph_app.alert_message:
        class: %jumph_app.session.alert_message.class%
        arguments:
            - @session
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]